name: docs-build

on:
  pull_request:
    branches: [master]

env:
  HIREDIS_VER: 1.0.2
  REDIS_PP_VER: 1.3.3
  ROCKSDB_VER: 6.29.3
  RDKAFKA_VER: 1.8.2
  CUDA_SHORT_VERSION: 11.6
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/lib:/repos/dist/lib
  CUDA_HOME: /usr/local/cuda
  CUDA_PATH: $CUDA_HOME
  CUDA_CUDA_LIBRARY: ${CUDA_HOME}/lib64/stubs
  PATH: ${CUDA_HOME}/lib64/:${PATH}:${CUDA_HOME}/bin:/usr/lib/x86_64-linux-gnu/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Git submodules
        run: |
          git submodule update --init --recursive
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages
        run: |
          apt update -y --fix-missing && \
          apt install -y --no-install-recommends \
            openssl \
            pkg-config \
            protobuf-compiler \
            # [ HugeCTR dependencies ]
            #   Required to build RocksDB.
            libgflags-dev \
            zlib1g-dev libbz2-dev libsnappy-dev liblz4-dev libzstd-dev \
            #   Required to build RdKafka.
            zlib1g-dev libzstd-dev \
            libssl-dev libsasl2-dev \
            #   Required to build Protocol Buffers.
            autoconf automake libtool \
            # [ HugeCTR ]
            libaio-dev libtbb-dev \
            clang-format \
            software-properties-common  && \
            apt remove --purge cmake -y && \
            apt autoremove -y && \
            apt clean && \
            rm -rf /var/lib/apt/lists/*
      - name: Install cmake
        run: |
          apt remove --purge cmake -y && \
          wget http://www.cmake.org/files/v3.21/cmake-3.21.1.tar.gz && \
          tar xf cmake-3.21.1.tar.gz && cd cmake-3.21.1 && ./configure && make && make install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools==59.4.0 wheel
          python -m pip install -r docs/requirements-doc.txt
          python -m pip install tensorflow==2.8.0 ninja
      - name: Build HPS plugin for TF
        run: |
          pushd hierarchical_parameter_server
          python3 setup.py install
          popd
      - name: Building docs
        run: |
          make -C docs html
      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: html-build-artifact
          path: docs/build/html
          if-no-files-found: error
          retention-days: 1
      - name: Store PR information
        run: |
          mkdir ./pr
          echo ${{ github.event.number }}              > ./pr/pr.txt
          echo ${{ github.event.pull_request.merged }} > ./pr/merged.txt
          echo ${{ github.event.action }}              > ./pr/action.txt
      - name: Upload PR information
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
