name: docs-build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nvidia-merlin/hctr-doc-builder:0.2.1

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools==59.4.0 wheel
          python -m pip install -r docs/requirements-doc.txt
          python -m pip install tensorflow==2.8.0 ninja
      - name: Install packages
        run: |
          apt update
          apt install -y libxxhash-dev
      - name: Build HPS plugin for TF
        run: |
          pushd hierarchical_parameter_server
          python3 setup.py install
          popd
      - name: Building docs
        run: |
          make -C docs html
      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: html-build-artifact
          path: docs/build/html
          if-no-files-found: error
          retention-days: 1
      - name: Store PR information
        run: |
          mkdir ./pr
          echo ${{ github.event.number }}              > ./pr/pr.txt
          echo ${{ github.event.pull_request.merged }} > ./pr/merged.txt
          echo ${{ github.event.action }}              > ./pr/action.txt
      - name: Upload PR information
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
